# Generated by Django 5.0.6 on 2024-05-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_patient_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("others", "Others")],
                max_length=10,
            ),
        ),
    ]
