# Generated by Django 5.0.6 on 2024-05-21 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_doctor_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("patient", "doctor", "date", "time")},
        ),
    ]
